### ISSUE TITLE
Search page unstyled for some users

### ISSUE THREAD

**Issue by DutssZ** [aidanhorton/ecosia-darkmode-extensions#9]
![Captura de tela 2021-02-12 112758](https://user-images.githubusercontent.com/43860020/107780577-9ec72180-6d25-11eb-8666-fb821b69d042.jpg)
New visual problem, altough the "new tab" page and ecosia's homepage are on dark mode the seach tab is all light besides the toolbar lines and search box text

**Comment by aidanhorton** [comment]
Hiya! Sorry about the late reply.

This is a weird one.
My home page, and other peoples homepages have been confirmed to be working and OK.

I've seen a similar issue before where some people get an issue like this, some people don't - the reason people got it is because Ecosia releases regional updates from time to time to test an update with a small subset of users before full release - I've seen the same thing with the images page before.

Since I can't repro it on my PC, or any other PC, it will be a tough one to fix until they roll out this update nationally - but you could help me out first of all by sending me the HTML + CSS for that webpage if you know how to do it.

**Comment by thundercrypt** [comment]
MAJOR ISSUE: Hi, I'm experiening a huge bug here. Attatching screenshot for further details.

![image](https://user-images.githubusercontent.com/77282722/109924848-ee768880-7ce6-11eb-933f-ec73c2441c07.png)

**Comment by thundercrypt** [comment]
> MAJOR ISSUE: Hi, I'm experiening a huge bug here. Attatching screenshot for further details.
> 

Might be related to this...

**Comment by aidanhorton** [comment]
Looks like this was due to Ecosia slowly releasing a beta for the Images page - this all happened a while back and has been rolled-out now, meaning this is no longer an issue.
